# -*- coding: utf-8 -*-
"""DS1-ABLAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsQ2yYhzOGSAEociRjcQctle5H-x3fVi
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
karkavelrajaj_amazon_sales_dataset_path = kagglehub.dataset_download('karkavelrajaj/amazon-sales-dataset')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pandas as pd

df = pd.read_csv("/kaggle/input/amazon-sales-dataset/amazon.csv")
df

df.head()

df.tail()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

for col in ['discounted_price',	'actual_price',	'discount_percentage','rating',	'rating_count']:
  df[col]=df[col].astype(str).str.replace('₹','').str.replace('%','').str.replace(',','').str.replace('nan','0')
  df[col] = pd.to_numeric(df[col].str.replace('[^0-9.]','',regex=True),errors='coerce').fillna(0)

df.isnull().sum()

df.describe(include="O")

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
plt.figure(figsize=(12, 6))
ax = sns.countplot(data=df, x='rating', palette='deep')
plt.title('Number of rating')
plt.show()

plt.figure(figsize=(10,8))
sns.histplot(data=df, x="discount_percentage", color="chocolate", kde=True)
plt.xlabel("discount_percentage")
plt.ylabel("Frequancy")
plt.title("Discount Percentage Distribution")
plt.show()

plt.figure(figsize=(10,8))
sns.histplot(data=df, x="discounted_price", color="gold", kde=True)
plt.xlabel("discount_price")
plt.ylabel("Frequancy")
plt.title("Discount Price Distribution")
plt.show()

plt.figure(figsize=(10,8))
sns.histplot(data=df, x="rating", color="darkred", kde=True)
plt.xlabel("rating")
plt.ylabel("Frequancy")
plt.title("rating Distribution")
plt.show()

discount_percentage_counts = df['discount_percentage'].value_counts().head(10)
plt.pie(discount_percentage_counts.values, labels=discount_percentage_counts.index, autopct='%1.2f%%')
plt.title('Top 10 discount_percentage Distribution')
plt.legend(bbox_to_anchor=(1.1, 1))
plt.show()

plt.figure(figsize=(8,6))
numerical_cols=['rating','rating_count','actual_price','discount_percentage','discounted_price']
corr_matrix=df[numerical_cols].corr()
sns.heatmap(corr_matrix,annot=True,fmt='.2f',cmap='coolwarm')
plt.title("Correlation Heatmap of Numerical Features")
plt.show()

plt.figure(figsize=(10,6))
sns.lineplot(x='discount_percentage',y='discounted_price',data=df,marker="o", color="darkblue")
plt.xlabel('discount_percentage')
plt.ylabel('discounted_price')
plt.title("Discounted Price vs. Discount Percentage")
plt.show()

plt.figure(figsize=(10,6))
sns.lineplot(x='rating',y='discounted_price',data=df,marker="o", color="dimgrey")
plt.xlabel('rating')
plt.ylabel('discounted_price')
plt.title("Discounted Price vs. Rating")
plt.show()